x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile

  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-api-server:8080/execution/
    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}
    AIRFLOW__API__SECRET_KEY: ${AIRFLOW_API_SECRET_KEY}
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
    - ./data:/opt/airflow/project/data
    - ./artifacts:/opt/airflow/project/artifacts

  depends_on:
    postgres:
      condition: service_healthy


services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: always


  airflow-init:
    <<: *airflow-common
    command: db migrate
    restart: "no"


  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully


  airflow-api-server:
    <<: *airflow-common
    command: api-server
    restart: always

    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

    ports:
      - "8082:8080"


  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always

    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully


  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always

    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully


volumes:
  postgres-db-volume: